config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
sqa_criteria:
  QC.Sty:
    repos:
      this_repo:
        commands:
        - flake8 qc_*
        container: qc.sty_skinny-corn-llama
  QC.Sec:
    repos:
      this_repo:
        commands:
        - bandit qc_doc_find_doc_files/tests/test_validator.py --severity-level high --confidence-level high
        container: qc.sec_bandit
timeout: 600
